name: flutter_webview
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_remote_config: ^2.0.13
  flutter:
    sdk: flutter
  onesignal_flutter: ^3.4.0
  webview_flutter: ^3.0.4

dev_dependencies:
  dart_code_metrics: ^4.17.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
